# Generated by Django 6.0.2 on 2026-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('status_code', models.IntegerField()),
                ('response_size', models.IntegerField()),
            ],
        ),
    ]
